# this file is for aws codebuild, maybe is better like this.

version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - Nothing to do using latest Amazon Linux Docker Image for CodeBuild which has all AWS Tools - https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile"
  build:
    commands:
      # create pull request to develop
      - echo "Creating pull request from feature/new_feature to develop"
      - |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d '{"title": "Automated PR from feature/new_feature to develop", "head": "feature/new_feature", "base": "develop"}' \
          https://api.github.com/repos/$GIT_USER_NAME/$REPO_NAME/pulls
  post_build:
    commands:
      # Push Docker Image to ECR Repository
      - echo "Build completed on `date`"
      
      
