apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  type: NodePort
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-frontend
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - host: dev.salvadormenendez.social
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-frontend
                port:
                  number: 80