# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets
#   namespace: default
# spec:
#   provider: aws
#   secretObjects:
#   - secretName: api-token # Name of the Kubernetes secret to mount
#     type: Opaque # Type of Kubernetes secret
#     data: # List of secrets to mount as files in the pod
#     - objectName: cloudflare # Name of the secret in AWS Secrets Manager
#       key: SECRET_TOKEN # Key in the Kubernetes secret where the secret should be mounted
#   parameters:
#     objects: |
#       - objectName: cloudflare
#         objectType: secretsmanager
#         objectAlias: cloudflare

# # this code block will fetch the secret named secret-token from AWS Secrets Manager and 
# # store it in the Kubernetes secret named api-token with the key SECRET_TOKEN.


# for more details check this article: https://towardsaws.com/aws-secret-manager-on-eks-e050b38bc77d


apiVersion: secrets-store.csi.x-k8s.io/v1  # specifies the API version to use
kind: SecretProviderClass  # specifies the Kubernetes object type to create
metadata:
  name: eks-test-secret  # specifies the name for the object being created
spec:
  provider: aws  # specifies the provider for the object
  secretObjects:  
  - secretName: cloudflare  
    type: Opaque  # specifies the type of secret object to be created in Kubernetes
    data:  
    - objectName: cloudflare_email  # specifies the name of the object in the secret manager
      key: cloudflare_email  # specifies the key in the Kubernetes secret where the object should be mounted
    - objectName: cloudflare_key  # specifies the name of the object in the secret manager
      key: cloudflare_key  # specifies the key in the Kubernetes secret where the object should be mounted
  parameters:  # specifies the additional configuration parameters for the object
    objects: |  
        - objectName: "cloudflare"  
          objectType: "secretsmanager"  
          jmesPath:  
            - path: "cloudflare_email"  
              objectAlias: "cloudflare_email"  
            - path: "cloudflare_key"  
              objectAlias: "cloudflare_key"  
